import Home from "./home/index";
import Container from "../components/Container";
import Head from "next/head";
const App = () => {
  return (
    <>
      <Head>
        <title>Don Omar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/ai.png" />
      </Head>

      <Container>
        <Home></Home>
      </Container>
    </>
  );
};

export default App;
